# Default values for clickhouse-gke.

clickhouse:
  clusterName: clickhouse-cluster
  shards: 3
  replicas: 2
  
  image:
    repository: clickhouse/clickhouse-server
    tag: 23.8.9.54
    pullPolicy: IfNotPresent

  storage:
    class: standard-rwo
    size: 500Gi

  resources:
    requests:
      memory: 16Gi
      cpu: 4
    limits:
      memory: 32Gi
      cpu: 8

keeper:
  replicas: 3
  storage:
    class: standard-rwo
    size: 10Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 2

service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
